build_stable:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/sukso96100/forest-nodejs:latest .
    - docker push registry.gitlab.com/sukso96100/forest-nodejs:latest
  only:
    - master

build_unstable:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/sukso96100/forest-nodejs:unstable .
    - docker push registry.gitlab.com/sukso96100/forest-nodejs:unstable
  only:
    - unstable
